// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejvvgjnudsakyvtfwhse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdnZnam51ZHNha3l2dGZ3aHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjExOTYsImV4cCI6MjA2NDQ5NzE5Nn0.A-H3vc5tyJco8vmilg6R2GFTmZhEO02Tx077L2LB0xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);